#

pluginName = Ape4_B Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Principal_type = Principal
_UI_Entidad_type = Entidad
_UI_Atributo_type = Atributo
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Principal_name_feature = Name
_UI_Principal_posee_feature = Posee
_UI_Entidad_name_feature = Name
_UI_Entidad_contiene_feature = Contiene
_UI_Entidad_redirige_feature = Redirige
_UI_Atributo_name_feature = Name
_UI_Atributo_longitud_feature = Longitud
_UI_Atributo_tipoDato_feature = Tipo Dato
_UI_Atributo_requerido_feature = Requerido
_UI_Unknown_feature = Unspecified

_UI_TipoDato_STRING_literal = STRING
_UI_TipoDato_DOUBLE_literal = DOUBLE
_UI_TipoDato_INTEGER_literal = INTEGER
_UI_TipoDato_BOOLEAN_literal = BOOLEAN
_UI_TipoDato_TIME_literal = TIME
_UI_TipoDato_DATE_literal = DATE
